apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jira-bot.fullname" . }}-config
  labels:
    {{- include "jira-bot.labels" . | nindent 4 }}
data:
  JIRA_BOT_JIRA_USERNAME: {{ .Values.config.jira.username }}
  JIRA_BOT_JIRA_BASE_URL: {{ .Values.config.jira.baseURL }}
  JIRA_BOT_JIRA_DEFAULT_PROJECT: {{ .Values.config.jira.defaultProject }}
  JIRA_BOT_JIRA_DEFAULT_ISSUE_TYPE: {{ .Values.config.jira.defaultIssueType }}
  {{- if .Values.config.log_level }}
  JIRA_BOT_LOG_LEVEL: {{ .Values.config.logLevel }}
  {{- end }}
  {{- if .Values.config.listenHTTP }}
  JIRA_BOT_LISTEN_HTTP: {{ .Values.config.listenHTTP }}
  {{- end }}
