apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jira-bot.fullname" . }}-secrets
  labels:
    {{- include "jira-bot.labels" . | nindent 4 }}
stringData:
  JIRA_BOT_GITHUB_WEBHOOK_SECRET: {{ .Values.secrets.github.webhookSecret | quote }}
  JIRA_BOT_JIRA_TOKEN: {{ .Values.secrets.jiraToken | quote }}
data:
  JIRA_BOT_GITHUB_PRIVATE_KEY: {{ .Values.secrets.github.privateKeyBase64 | quote }}
