apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jira-bot.fullname" . }}-secrets
  labels:
    {{- include "jira-bot.labels" . | nindent 4 }}
stringData:
  JIRA_BOT_GITHUB_TOKEN: {{ .Values.secrets.github_token | quote }}
  JIRA_BOT_JIRA_TOKEN: {{ .Values.secrets.jira_token | quote }}
