apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jira-bot.fullname" . }}-secrets
  labels:
    {{- include "jira-bot.labels" . | nindent 4 }}
data:
  JIRA_BOT_GITHUB_WEBHOOK_SECRET: {{ .Values.secrets.github.webhookSecret | b64enc | quote }}
  JIRA_BOT_GITHUB_PRIVATE_KEY: {{ .Values.secrets.github.privateKeyBase64 | quote }}
  {{- if .Values.secrets.github.appClientSecret }}
  JIRA_BOT_GITHUB_APP_CLIENT_SECRET: {{ .Values.secrets.github.appClientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.jira.clientID }}
  JIRA_BOT_JIRA_CLIENT_ID: {{ .Values.secrets.jira.clientID | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.jira.clientSecret }}
  JIRA_BOT_JIRA_CLIENT_SECRET: {{ .Values.secrets.jira.clientSecret | b64enc | quote }}
  {{- end }}
